//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAdvisingSystem.WCCard {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageSize", Namespace="http://schemas.datacontract.org/2004/07/edu.csu.chico.ems.services.WildCatCardSer" +
        "vice")]
    public enum ImageSize : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Size100x100 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Size150x150 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Size200x200 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Size300x300 = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WildCatImage", Namespace="http://schemas.datacontract.org/2004/07/edu.csu.chico.ems.services.WildCatCardSer" +
        "vice")]
    [System.SerializableAttribute()]
    public partial class WildCatImage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageName {
            get {
                return this.ImageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageNameField, value) != true)) {
                    this.ImageNameField = value;
                    this.RaisePropertyChanged("ImageName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WildCatCardServiceFault", Namespace="http://schemas.datacontract.org/2004/07/edu.csu.chico.ems.services.WildCatCardSer" +
        "vice")]
    [System.SerializableAttribute()]
    public partial class WildCatCardServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultID {
            get {
                return this.FaultIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultIDField, value) != true)) {
                    this.FaultIDField = value;
                    this.RaisePropertyChanged("FaultID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultMessage {
            get {
                return this.FaultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageField, value) != true)) {
                    this.FaultMessageField = value;
                    this.RaisePropertyChanged("FaultMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ems.csuchico.edu/services/WildCatCardService/WildCatCard/2011/11/01", ConfigurationName="WCCard.IWildCatCard")]
    public interface IWildCatCard {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ems.csuchico.edu/services/WildCatCardService/WildCatCard/2011/11/01/IWildC" +
            "atCard/GetWildCatImageAny", ReplyAction="http://ems.csuchico.edu/services/WildCatCardService/WildCatCard/2011/11/01/IWildC" +
            "atCard/GetWildCatImageAnyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StudentAdvisingSystem.WCCard.WildCatCardServiceFault), Action="http://ems.csuchico.edu/services/WildCatCardService/WildCatCard/2011/11/01/IWildC" +
            "atCard/GetWildCatImageAnyWildCatCardServiceFaultFault", Name="WildCatCardServiceFault", Namespace="http://schemas.datacontract.org/2004/07/edu.csu.chico.ems.services.WildCatCardSer" +
            "vice")]
        StudentAdvisingSystem.WCCard.WildCatImage GetWildCatImageAny(string Chico_State_ID, StudentAdvisingSystem.WCCard.ImageSize Size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ems.csuchico.edu/services/WildCatCardService/WildCatCard/2011/11/01/IWildC" +
            "atCard/GetWildCatImageStudent", ReplyAction="http://ems.csuchico.edu/services/WildCatCardService/WildCatCard/2011/11/01/IWildC" +
            "atCard/GetWildCatImageStudentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StudentAdvisingSystem.WCCard.WildCatCardServiceFault), Action="http://ems.csuchico.edu/services/WildCatCardService/WildCatCard/2011/11/01/IWildC" +
            "atCard/GetWildCatImageStudentWildCatCardServiceFaultFault", Name="WildCatCardServiceFault", Namespace="http://schemas.datacontract.org/2004/07/edu.csu.chico.ems.services.WildCatCardSer" +
            "vice")]
        StudentAdvisingSystem.WCCard.WildCatImage GetWildCatImageStudent(string Chico_State_ID, StudentAdvisingSystem.WCCard.ImageSize Size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ems.csuchico.edu/services/WildCatCardService/WildCatCard/2011/11/01/IWildC" +
            "atCard/GetWildCatImageFacultyStaff", ReplyAction="http://ems.csuchico.edu/services/WildCatCardService/WildCatCard/2011/11/01/IWildC" +
            "atCard/GetWildCatImageFacultyStaffResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StudentAdvisingSystem.WCCard.WildCatCardServiceFault), Action="http://ems.csuchico.edu/services/WildCatCardService/WildCatCard/2011/11/01/IWildC" +
            "atCard/GetWildCatImageFacultyStaffWildCatCardServiceFaultFault", Name="WildCatCardServiceFault", Namespace="http://schemas.datacontract.org/2004/07/edu.csu.chico.ems.services.WildCatCardSer" +
            "vice")]
        StudentAdvisingSystem.WCCard.WildCatImage GetWildCatImageFacultyStaff(string Chico_State_ID, StudentAdvisingSystem.WCCard.ImageSize Size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ems.csuchico.edu/services/WildCatCardService/WildCatCard/2011/11/01/IWildC" +
            "atCard/GetChicoStateIdsChgdImgsBtwn", ReplyAction="http://ems.csuchico.edu/services/WildCatCardService/WildCatCard/2011/11/01/IWildC" +
            "atCard/GetChicoStateIdsChgdImgsBtwnResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StudentAdvisingSystem.WCCard.WildCatCardServiceFault), Action="http://ems.csuchico.edu/services/WildCatCardService/WildCatCard/2011/11/01/IWildC" +
            "atCard/GetChicoStateIdsChgdImgsBtwnWildCatCardServiceFaultFault", Name="WildCatCardServiceFault", Namespace="http://schemas.datacontract.org/2004/07/edu.csu.chico.ems.services.WildCatCardSer" +
            "vice")]
        string[] GetChicoStateIdsChgdImgsBtwn(string start_date, string end_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ems.csuchico.edu/services/WildCatCardService/WildCatCard/2011/11/01/IWildC" +
            "atCard/GetChicoStateIdsChgdImgsSince", ReplyAction="http://ems.csuchico.edu/services/WildCatCardService/WildCatCard/2011/11/01/IWildC" +
            "atCard/GetChicoStateIdsChgdImgsSinceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StudentAdvisingSystem.WCCard.WildCatCardServiceFault), Action="http://ems.csuchico.edu/services/WildCatCardService/WildCatCard/2011/11/01/IWildC" +
            "atCard/GetChicoStateIdsChgdImgsSinceWildCatCardServiceFaultFault", Name="WildCatCardServiceFault", Namespace="http://schemas.datacontract.org/2004/07/edu.csu.chico.ems.services.WildCatCardSer" +
            "vice")]
        string[] GetChicoStateIdsChgdImgsSince(string start_date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IWildCatCardChannel : StudentAdvisingSystem.WCCard.IWildCatCard, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WildCatCardClient : System.ServiceModel.ClientBase<StudentAdvisingSystem.WCCard.IWildCatCard>, StudentAdvisingSystem.WCCard.IWildCatCard {
        
        public WildCatCardClient() {
        }
        
        public WildCatCardClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WildCatCardClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WildCatCardClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WildCatCardClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StudentAdvisingSystem.WCCard.WildCatImage GetWildCatImageAny(string Chico_State_ID, StudentAdvisingSystem.WCCard.ImageSize Size) {
            return base.Channel.GetWildCatImageAny(Chico_State_ID, Size);
        }
        
        public StudentAdvisingSystem.WCCard.WildCatImage GetWildCatImageStudent(string Chico_State_ID, StudentAdvisingSystem.WCCard.ImageSize Size) {
            return base.Channel.GetWildCatImageStudent(Chico_State_ID, Size);
        }
        
        public StudentAdvisingSystem.WCCard.WildCatImage GetWildCatImageFacultyStaff(string Chico_State_ID, StudentAdvisingSystem.WCCard.ImageSize Size) {
            return base.Channel.GetWildCatImageFacultyStaff(Chico_State_ID, Size);
        }
        
        public string[] GetChicoStateIdsChgdImgsBtwn(string start_date, string end_date) {
            return base.Channel.GetChicoStateIdsChgdImgsBtwn(start_date, end_date);
        }
        
        public string[] GetChicoStateIdsChgdImgsSince(string start_date) {
            return base.Channel.GetChicoStateIdsChgdImgsSince(start_date);
        }
    }
}
